### PR TITLE
Dark themes .pre

### PR DESCRIPTION
**Pull request by oeai**
Here i implemented 3 dark themes, slightly different
i've added 3 vars into previous postprocessor files and pushed them into few css
so default theme should be just like it is
these tweaks was minimal (diffusion, menu, tasks), but they change look, so if any other will be interested - they can continue with more css tweaks.
up symbiants com_2015-10-21_02-03-06
up symbiants com_2015-10-21_02-02-35
up symbiants com_2015-10-21_02-01-43

### CODE REVIEW

**Comment by chadlittle** [comment]
Please see https://secure.phabricator.com/book/phabcontrib/article/contributing_code/.

**Comment by chadlittle** [comment]
Please see https://secure.phabricator.com/book/phabcontrib/article/contributing_code/

**Comment by oeai** [comment]
it's not in russian  ,' )

**Comment by chadlittle** [comment]
Ok:

1) We don't accept code without coordination.
2) We don't accept pull requests on GitHub.
3) We're not interested in maintaining this feature in the upstream.

**Comment by oeai** [comment]
good to know (3) i didn't write too much, anyway it will be easier to insert this code for others

**Comment by chadlittle** [comment]
Sorry, it's just we've found maintaining code for infinity to be expensive on our side, so we're don't take many contributions unless it's well planned.

**Comment by oeai** [comment]
that's ok
about those long  *.php - that's just clones of default_postprocessor.php + few value changes
if anyone will analyze it

**Pull request closed without merging**
